FROM jenkins/jenkins:lts-jdk17

USER root

# #region Build Tooling Installation
RUN apt-get update && apt-get install -y --no-install-recommends \
    golang-go \
    zip \
    curl \
    gnupg \
    software-properties-common \
    && curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com bookworm main" | tee /etc/apt/sources.list.d/hashicorp.list \
    && apt-get update && apt-get install -y terraform \
    && rm -rf /var/lib/apt/lists/*

# Grant Jenkins access to host-mounted git directories
RUN git config --system --add safe.directory "*"
# #endregion

USER jenkins
